# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TwitterMessaging' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TwitterMessaging
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'RxRelay', '~> 5'

  target 'TwitterMessagingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TwitterMessagingUITests' do
    # Pods for testing
  end

end
